export const Colors = {
    light: {
        background: "#fafafa",
        foreground: "#0a0a0a",
        card: "#fdfdfd",
        cardForeground: "#0a0a0a",
        popover: "#fdfdfd",
        popoverForeground: "#0a0a0a",
        primary: "#fb2c36",
        primaryForeground: "#fafafa",
        secondary: "#f5f5f5",
        secondaryForeground: "#262626",
        muted: "#f1f5f9",
        mutedForeground: "#62748e",
        accent: "#fb2c36",
        accentForeground: "#fafafa",
        destructive: "#e7000b",
        destructiveForeground: "#ffffff",
        border: "#e2e8f0",
        input: "#e2e8f0",
        ring: "#fb2c36",
        chart1: "#fb2c36",
        chart2: "#f47700",
        chart3: "#00a3b0",
        chart4: "#009600",
        chart5: "#7f82e8",
        sidebar: "#f5f5f5",
        sidebarForeground: "#0a0a0a",
        sidebarPrimary: "#fb2c36",
        sidebarPrimaryForeground: "#fafafa",
        sidebarAccent: "#e2e8f0",
        sidebarAccentForeground: "#0a0a0a",
        sidebarBorder: "#e2e8f0",
        sidebarRing: "#fb2c36",
        shadowColor: "oklch(0 0 0)",
        // collective shadows
        // shadow2xs: "0 1px 4px 0px hsl(0 0% 0% / 0.05)",
        // shadowXs: "0 1px 4px 0px hsl(0 0% 0% / 0.05)",
        // shadowSm: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 1px 2px -1px hsl(0 0% 0% / 0.10)",
        // shadow: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 1px 2px -1px hsl(0 0% 0% / 0.10)",
        // shadowMd: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 2px 4px -1px hsl(0 0% 0% / 0.10)",
        // shadowLg: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 4px 6px -1px hsl(0 0% 0% / 0.10)",
        // shadowXl: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 8px 10px -1px hsl(0 0% 0% / 0.10)",
        // shadow2xl: "0 1px 4px 0px hsl(0 0% 0% / 0.25)",
        shadow2xs: [{
            offsetX: 0,
            offsetY: 1,
            blurRadius: 4,
            spreadDistance: 0,
            color: "hsl(0 0% 0% / 0.05)",
        }],

        shadowXs: [{
            offsetX: 0,
            offsetY: 1,
            blurRadius: 4,
            spreadDistance: 0,
            color: "hsl(0 0% 0% / 0.05)",
        }],
        shadow: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 2,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],
        shadowMd: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 2,
                blurRadius: 4,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],
        shadowLg: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 4,
                blurRadius: 6,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],
        shadowXl: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 8,
                blurRadius: 10,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],
        shadow2xl: [{
            offsetX: 0,
            offsetY: 1,
            blurRadius: 4,
            spreadDistance: 0,
            color: "hsl(0 0% 0% / 0.25)",
        }],
    },
    dark: {
        background: "#0a0a0a",
        foreground: "#fafafa",
        card: "#18181b",
        cardForeground: "#fafafa",
        popover: "#262626",
        popoverForeground: "#fafafa",
        primary: "#fb2c36",
        primaryForeground: "#fafafa",
        secondary: "#262626",
        secondaryForeground: "#fafafa",
        muted: "#27272a",
        mutedForeground: "#e7e5e4",
        accent: "#fb2c36",
        accentForeground: "#fafafa",
        destructive: "#ff6467",
        destructiveForeground: "#fafafa",
        border: "#404040",
        input: "#404040",
        ring: "#fb2c36",
        chart1: "#ff6662",
        chart2: "#ff9710",
        chart3: "#00bcc8",
        chart4: "#4cb332",
        chart5: "#9499fa",
        sidebar: "#171717",
        sidebarForeground: "#fafafa",
        sidebarPrimary: "#ff6467",
        sidebarPrimaryForeground: "#fafafa",
        sidebarAccent: "#262626",
        sidebarAccentForeground: "#e5e5e5",
        sidebarBorder: "#404040",
        sidebarRing: "#ff6467",
        shadowColor: "oklch(0 0 0)",
        // online shadows
        // shadow2xs: "0 1px 4px 0px hsl(0 0% 0% / 0.05)",
        // shadowXs: "0 1px 4px 0px hsl(0 0% 0% / 0.05)",
        // shadowSm: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 1px 2px -1px hsl(0 0% 0% / 0.10)",
        // shadow: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 1px 2px -1px hsl(0 0% 0% / 0.10)",
        // shadowMd: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 2px 4px -1px hsl(0 0% 0% / 0.10)",
        // shadowLg: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 4px 6px -1px hsl(0 0% 0% / 0.10)",
        // shadowXl: "0 1px 4px 0px hsl(0 0% 0% / 0.10), 0 8px 10px -1px hsl(0 0% 0% / 0.10)",
        // shadow2xl: "0 1px 4px 0px hsl(0 0% 0% / 0.25)",
        shadow2xs: [{
            offsetX: 0,
            offsetY: 1,
            blurRadius: 4,
            spreadDistance: 0,
            color: "hsl(0 0% 0% / 0.05)",
        }],

        shadowXs: [{
            offsetX: 0,
            offsetY: 1,
            blurRadius: 4,
            spreadDistance: 0,
            color: "hsl(0 0% 0% / 0.05)",
        }],

        shadowSm: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 2,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],

        shadow: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 2,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],

        shadowMd: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 2,
                blurRadius: 4,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],

        shadowLg: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 4,
                blurRadius: 6,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],

        shadowXl: [
            {
                offsetX: 0,
                offsetY: 1,
                blurRadius: 4,
                spreadDistance: 0,
                color: "hsl(0 0% 0% / 0.10)",
            },
            {
                offsetX: 0,
                offsetY: 8,
                blurRadius: 10,
                spreadDistance: -1,
                color: "hsl(0 0% 0% / 0.10)",
            },
        ],

        shadow2xl: [{
            offsetX: 0,
            offsetY: 1,
            blurRadius: 4,
            spreadDistance: 0,
            color: "hsl(0 0% 0% / 0.25)",
        }],
    },
} as const;
// from : https://tweakcn.com/themes/cmm2769u2000004jobride6q4

export type ColorsType = typeof Colors.light | typeof Colors.dark;